import {
  dateTimeSchema,
  nullableDateTimeSchema,
  nullableStringSchema,
  nullableUuidSchema,
  uuidSchema,
} from '@/common/swagger';

const roomStatusEnumValues = ['ACTIVE', 'ARCHIVED', 'READ_ONLY'];
const messageTypeEnumValues = ['TEXT', 'IMAGE', 'FILE', 'SYSTEM'];
const roleEnumValues = ['PATIENT', 'PROFESSIONAL'];

const chatParticipantSchema = {
  type: 'object',
  properties: {
    userId: uuidSchema('a74a289c-56a0-43cc-9db5-1c0b6b3eb9ac'),
    name: {
      type: 'string',
      example: 'Dra. Maria Oliveira',
    },
    avatarUrl: nullableStringSchema(
      'https://cdn.psique.com/avatars/profissional-01.jpg',
    ),
  },
  required: ['userId', 'name'],
};

const chatProfessionalSchema = {
  type: 'object',
  properties: {
    ...chatParticipantSchema.properties,
    specialty: nullableStringSchema('Terapia Cognitivo-Comportamental'),
  },
  required: ['userId', 'name'],
};

export const chatAttachmentSchema = {
  type: 'object',
  properties: {
    id: uuidSchema('274cf869-c30e-4039-9383-7642fcfd89d8'),
    fileName: {
      type: 'string',
      example: 'relatorio.pdf',
    },
    mimeType: {
      type: 'string',
      example: 'application/pdf',
    },
    sizeBytes: {
      type: 'integer',
      minimum: 1,
      example: 48213,
    },
    createdAt: dateTimeSchema('2026-06-08T11:30:00.000Z'),
    downloadUrl: {
      type: 'string',
      example: '/chat/attachments/274cf869-c30e-4039-9383-7642fcfd89d8',
    },
  },
  required: ['id', 'fileName', 'mimeType', 'sizeBytes', 'createdAt', 'downloadUrl'],
};

export const chatMessageSchema = {
  type: 'object',
  properties: {
    id: uuidSchema('563cc612-a06d-4213-a65d-fbff41f8e4d9'),
    roomId: uuidSchema('f52993d4-344b-4a38-a2e7-f0b063bc5f31'),
    senderId: uuidSchema('a74a289c-56a0-43cc-9db5-1c0b6b3eb9ac'),
    type: {
      type: 'string',
      enum: messageTypeEnumValues,
      example: 'TEXT',
    },
    content: nullableStringSchema('Olá! Consegue me atender hoje?'),
    isAutoGenerated: {
      type: 'boolean',
      example: false,
    },
    sentAt: dateTimeSchema('2026-06-08T11:30:00.000Z'),
    readAt: nullableDateTimeSchema('2026-06-08T11:32:00.000Z'),
    sender: {
      type: 'object',
      properties: {
        id: uuidSchema('a74a289c-56a0-43cc-9db5-1c0b6b3eb9ac'),
        name: {
          type: 'string',
          example: 'Paciente Teste',
        },
        avatarUrl: nullableStringSchema(
          'https://cdn.psique.com/avatars/paciente-01.jpg',
        ),
        role: {
          type: 'string',
          enum: roleEnumValues,
          example: 'PATIENT',
        },
      },
      required: ['id', 'name', 'role'],
    },
    attachments: {
      type: 'array',
      items: chatAttachmentSchema,
    },
  },
  required: [
    'id',
    'roomId',
    'senderId',
    'type',
    'isAutoGenerated',
    'sentAt',
    'sender',
    'attachments',
  ],
};

export const chatRoomSchema = {
  type: 'object',
  properties: {
    id: uuidSchema('f52993d4-344b-4a38-a2e7-f0b063bc5f31'),
    patientId: uuidSchema('8ff1d99c-53e2-4930-9f8f-98dc3f9dedab'),
    professionalId: uuidSchema('a74a289c-56a0-43cc-9db5-1c0b6b3eb9ac'),
    appointmentId: nullableUuidSchema('d6a4c43d-47de-4b91-af0f-d225d0dba2a1'),
    status: {
      type: 'string',
      enum: roomStatusEnumValues,
      example: 'ACTIVE',
    },
    createdAt: dateTimeSchema('2026-06-08T11:00:00.000Z'),
    updatedAt: dateTimeSchema('2026-06-08T11:30:00.000Z'),
    archivedAt: nullableDateTimeSchema('2026-06-10T12:00:00.000Z'),
    patient: chatParticipantSchema,
    professional: chatProfessionalSchema,
    lastMessage: {
      oneOf: [chatMessageSchema, { type: 'null' }],
    },
  },
  required: [
    'id',
    'patientId',
    'professionalId',
    'status',
    'createdAt',
    'updatedAt',
    'patient',
    'professional',
    'lastMessage',
  ],
};

export const createChatRoomRequestSchema = {
  type: 'object',
  properties: {
    professionalId: uuidSchema('a74a289c-56a0-43cc-9db5-1c0b6b3eb9ac'),
    patientId: uuidSchema('8ff1d99c-53e2-4930-9f8f-98dc3f9dedab'),
    appointmentId: nullableUuidSchema('d6a4c43d-47de-4b91-af0f-d225d0dba2a1'),
  },
  description:
    'Para pacientes, informe o `professionalId`. Para profissionais, informe o `patientId`.',
};

export const chatRoomListSchema = {
  type: 'array',
  items: chatRoomSchema,
};

export const chatMessageListSchema = {
  type: 'array',
  items: chatMessageSchema,
};

export const uploadChatAttachmentRequestSchema = {
  type: 'object',
  properties: {
    file: {
      type: 'string',
      format: 'binary',
      description:
        'Aceita apenas PDF, JPG, JPEG ou PNG com validação de assinatura binária.',
    },
    caption: {
      type: 'string',
      maxLength: 4000,
      nullable: true,
      example: 'Segue o documento solicitado.',
    },
  },
  required: ['file'],
};
